kind: BuildConfig
apiVersion: build.openshift.io/v1
metadata:
  name: batching-runtime
spec:
  nodeSelector: null
  output:
    to:
      kind: ImageStreamTag
      name: 'batching-runtime:latest'
  resources: {}
  successfulBuildsHistoryLimit: 5
  failedBuildsHistoryLimit: 5
  strategy:
    type: Docker
    dockerStrategy:
      dockerfilePath: Containerfile
      # uncomment the following lines if working in a proxied environment
      #env:
      #  - name: NO_PROXY
      #    value: {list of domains}
  postCommit: {}
  source:
    type: Git
    git:
      uri: 'https://github.com/mamurak/odh-ml-pipelines-seldon.git'
    contextDir: '/container-images/batching-runtime'
    sourceSecret:
      name: bitbucket-access
  runPolicy: Serial
