apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: inference-service
spec:
  destination:
    name: ''
    namespace: odh-ml
    server: 'https://kubernetes.default.svc'
  source:
    path: /manifests
    repoURL: 'OPS_REPO_URL'
    targetRevision: HEAD
  project: odh-ml
  syncPolicy:
    automated:
      prune: false
      selfHeal: false
