apiVersion: kfdef.apps.kubeflow.org/v1
kind: KfDef
metadata:
  name: pipelines
spec:
  applications:
    - kustomizeConfig:
        repoRef:
          name: manifests
          path: odh-common
      name: odh-common
    - kustomizeConfig:
        overlays:
          - metadata-store-mysql
          - ml-pipeline-ui
          - object-store-minio
        repoRef:
          name: manifests
          path: ml-pipelines
      name: ml-pipelines
  repos:
    - name: manifests
      uri: 'https://github.com/opendatahub-io/odh-manifests/tarball/master'
