FROM quay.io/thoth-station/s2i-lab-elyra:v0.1.5

USER root

RUN pip uninstall -y jupyterlab-tabnine \
 && pip install pip==22.2.2 setuptools==65.3.0

COPY requirements.txt ./requirements.txt
RUN pip install --no-cache-dir -r ./requirements.txt

USER 8888
